# Generated by Django 6.0.6 on 2026-07-04 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_client_id_alter_designation_id_alter_salary_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='employeeID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee'),
        ),
    ]
