# Generated by Django 6.0.6 on 2026-07-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_salary_employeeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='calculatedAllowance',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='salary',
            name='calculatedESI',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='salary',
            name='calculatedHRA',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='salary',
            name='calculatedPF',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='salary',
            name='claculatedBasic',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='salary',
            name='monthDays',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='salary',
            name='netPay',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8),
        ),
    ]
