# Generated by Django 6.0.6 on 2026-07-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_salary_calculatedallowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='deductions',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='salary',
            name='totalA',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
