# Generated by Django 6.0.6 on 2026-07-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_salary_deductions_salary_totala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='calculatedAllowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='salary',
            name='calculatedESI',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='salary',
            name='calculatedHRA',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='salary',
            name='calculatedPF',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='salary',
            name='claculatedBasic',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='salary',
            name='deductions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salary',
            name='netPay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='salary',
            name='totalA',
            field=models.IntegerField(default=0),
        ),
    ]
