# Generated by Django 6.0.6 on 2026-07-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_salary_calculatedallowance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='claculatedBasic',
            new_name='calculatedBasic',
        ),
    ]
